/**
 * Canonical domain event names used for notifications and system signals.
 * Channels, recipients, and delivery logic live elsewhere.
 */
module.exports = {
  // Audit events
  AUDIT_ASSIGNED: 'AUDIT_ASSIGNED',
  AUDIT_CHECKED_IN: 'AUDIT_CHECKED_IN',
  AUDIT_SUBMITTED: 'AUDIT_SUBMITTED',
  AUDIT_APPROVED: 'AUDIT_APPROVED',
  AUDIT_REJECTED: 'AUDIT_REJECTED',

  // Corrective action events
  CORRECTIVE_ACTION_CREATED: 'CORRECTIVE_ACTION_CREATED',
  CORRECTIVE_ACTION_DUE_SOON: 'CORRECTIVE_ACTION_DUE_SOON',
  CORRECTIVE_ACTION_OVERDUE: 'CORRECTIVE_ACTION_OVERDUE',

  // Task events (Phase 17: Notification Rules)
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_CREATED: 'TASK_CREATED',

  // CRM assignment (scheduled automation parity with TASK_ASSIGNED)
  PEOPLE_ASSIGNED: 'PEOPLE_ASSIGNED',
  DEAL_ASSIGNED: 'DEAL_ASSIGNED',
  ORGANIZATION_ASSIGNED: 'ORGANIZATION_ASSIGNED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_DUE_SOON: 'TASK_DUE_SOON',
  PLAYBOOK_ACTION_ALERT: 'PLAYBOOK_ACTION_ALERT',

  /** @mentioned in a record comment (Activity) */
  RECORD_COMMENT_MENTION: 'RECORD_COMMENT_MENTION',

  // Helpdesk case events
  CASE_CREATED: 'CASE_CREATED',
  CASE_ASSIGNED: 'CASE_ASSIGNED',
  CASE_STATUS_CHANGED: 'CASE_STATUS_CHANGED',
  CASE_REOPENED: 'CASE_REOPENED',
  CASE_ESCALATED: 'CASE_ESCALATED',
  CASE_SLA_WARNING: 'CASE_SLA_WARNING',
  CASE_SLA_BREACHED: 'CASE_SLA_BREACHED',
  CASE_SLA_ESCALATION: 'CASE_SLA_ESCALATION',
  CASE_SLA_LEADERSHIP_ESCALATION: 'CASE_SLA_LEADERSHIP_ESCALATION',
  CASE_EMAIL_RECEIVED: 'CASE_EMAIL_RECEIVED',
  CASE_CHAT_MESSAGE_RECEIVED: 'CASE_CHAT_MESSAGE_RECEIVED',
  CASE_PORTAL_AGENT_REPLY: 'CASE_PORTAL_AGENT_REPLY',
  CASE_PORTAL_STATUS_UPDATE: 'CASE_PORTAL_STATUS_UPDATE',

  // Live Chat addon events
  LIVE_CHAT_SESSION_STARTED: 'LIVE_CHAT_SESSION_STARTED',
  LIVE_CHAT_SESSION_ASSIGNED: 'LIVE_CHAT_SESSION_ASSIGNED',
  LIVE_CHAT_MESSAGE_RECEIVED: 'LIVE_CHAT_MESSAGE_RECEIVED',
  LIVE_CHAT_SESSION_ENDED: 'LIVE_CHAT_SESSION_ENDED',
  LIVE_CHAT_OUTCOME_SET: 'LIVE_CHAT_OUTCOME_SET',

  // Internal Chat addon events
  INTERNAL_CHAT_MENTIONED: 'INTERNAL_CHAT_MENTIONED',
  INTERNAL_CHAT_MESSAGE_POSTED: 'INTERNAL_CHAT_MESSAGE_POSTED',

  // Telephony addon events
  TELEPHONY_INCOMING_CALL: 'TELEPHONY_INCOMING_CALL',
  TELEPHONY_CALL_ANSWERED: 'TELEPHONY_CALL_ANSWERED',
  TELEPHONY_CALL_ENDED: 'TELEPHONY_CALL_ENDED',
  TELEPHONY_CALL_MISSED: 'TELEPHONY_CALL_MISSED',
  TELEPHONY_RECORDING_READY: 'TELEPHONY_RECORDING_READY',
  TELEPHONY_VOICEMAIL_RECEIVED: 'TELEPHONY_VOICEMAIL_RECEIVED',
  TELEPHONY_TRANSCRIPT_READY: 'TELEPHONY_TRANSCRIPT_READY',
  TELEPHONY_SUMMARY_READY: 'TELEPHONY_SUMMARY_READY',


  // Announcements & Alerts addon events
  ANNOUNCEMENT_PUBLISHED: 'ANNOUNCEMENT_PUBLISHED',
  ANNOUNCEMENT_ACKNOWLEDGED: 'ANNOUNCEMENT_ACKNOWLEDGED',
  ANNOUNCEMENT_CTA_CLICKED: 'ANNOUNCEMENT_CTA_CLICKED',

  // Other events
  EVIDENCE_UPLOADED: 'EVIDENCE_UPLOADED',
  PORTAL_ACCOUNT_CREATED: 'PORTAL_ACCOUNT_CREATED',
  USER_ADDED_TO_APP: 'USER_ADDED_TO_APP',

  // System events
  SYSTEM_TRIAL_EXPIRING: 'SYSTEM_TRIAL_EXPIRING',
  SYSTEM_SUBSCRIPTION_SUSPENDED: 'SYSTEM_SUBSCRIPTION_SUSPENDED',

  // Digest events
  DIGEST_DAILY: 'DIGEST_DAILY',
  DIGEST_WEEKLY: 'DIGEST_WEEKLY',

  /** Workspace inbox: user's snooze window ended; thread is visible in default folders again. */
  EMAIL_THREAD_SNOOZE_ENDED: 'EMAIL_THREAD_SNOOZE_ENDED',

  // Webform events
  WEBFORM_SUBMISSION: 'WEBFORM_SUBMISSION',

  // Marketing campaign approval
  MARKETING_CAMPAIGN_SUBMITTED_FOR_REVIEW: 'MARKETING_CAMPAIGN_SUBMITTED_FOR_REVIEW',
  MARKETING_CAMPAIGN_APPROVED: 'MARKETING_CAMPAIGN_APPROVED',
  MARKETING_CAMPAIGN_REJECTED: 'MARKETING_CAMPAIGN_REJECTED',

  // Learning (LMS)
  LEARNING_ENROLLED: 'LEARNING_ENROLLED',
  LEARNING_COURSE_PUBLISHED: 'LEARNING_COURSE_PUBLISHED',
  LEARNING_COURSE_COMPLETED: 'LEARNING_COURSE_COMPLETED',
  LEARNING_ASSIGNMENT_OVERDUE: 'LEARNING_ASSIGNMENT_OVERDUE',
};

